# Generated by Django 3.0.5 on 2022-12-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.CharField(default='https://asdicourse.com/default.svg', max_length=500),
        ),
    ]
